//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Development_AFE68746_76344ab1_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOw,_aP8YMXVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Brain Storm_91F74CC_dd2443e3_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOw,_ifAEUXVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Concept Art_8A625A15_5e67292c_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_j-bA8HV4EeikbeB96ldyOw,_m0qIYXkUEeiMcpQeZPOdbgActivity"]="./../../GamesUp/deliveryprocesses/resources/Community Meeting_DBA61E78_6de0a55_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOw,_hnnhoXV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Refine Concept_FD0FAB35_fe1bd896_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_kPtasHV3EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Iteration Dev_92A4AE12_58c4c417_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_lkgN8HV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Publish_72AB7642_38f939ad_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOw,_7qxwQXVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Community Meeting_AB9B1131_7f9fe048_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_kPtasHV3EeikbeB96ldyOw,_km1jUHl_EeiCROWijA9fGgActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Brief_E77B20ED_5fcf5e58_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Iteration_C75A008_d295b60d_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_lkgN8HV4EeikbeB96ldyOw,_0hXl0XldEeiPve0VZ9wu1AActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Publish_BB466C94_3f4d3d95_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_j-bA8HV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Demo_60C4651E_27122889_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_lkgN8HV4EeikbeB96ldyOw,_W37KAXmEEeiCROWijA9fGgActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Update_810B660B_512370c_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_kPtasHV3EeikbeB96ldyOw,_1CATMXV3EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game System Project_BAA5923B_32f9cfa6_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOw,_-E9TsnVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Refine Concept_2AF1923F_fef66156_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_j-bA8HV4EeikbeB96ldyOw,_Ts5NUXkUEeiMcpQeZPOdbgActivity"]="./../../GamesUp/deliveryprocesses/resources/Publishers Meet_ACBD47B9_d7f53396_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/LifeCycleGameUP_EF704A17_ef704a17_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOw,__OqGsnVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Engine Choose_28C98A52_fcce5969_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_j-bA8HV4EeikbeB96ldyOw,_hmzjcXkUEeiMcpQeZPOdbgActivity"]="./../../GamesUp/deliveryprocesses/resources/Publish Demo_90D5F188_bc0ddd65_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOw,_UNUfsXV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Community Meeting_4628F6FB_4735245c_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOw,_QsUeJHV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game System Project_AA880F5C_ab943cbd_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_kPtasHV3EeikbeB96ldyOw,_7AJsoXV3EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Script_F0486EC7_689cac32_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_lkgN8HV4EeikbeB96ldyOw,_3DmcMXkUEeiMcpQeZPOdbgActivity"]="./../../GamesUp/deliveryprocesses/resources/Ga_6B3CFF30_ef43d031_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_Ll-eIXVyEeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Design_FEA2D658_c4f099c3_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_kPtasHV3EeikbeB96ldyOw,_pHJDsXV3EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Art Development_8C3D48C2_491862d_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOw,_54qQQHmBEeiCROWijA9fGgActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Brief_2D787197_2e849ef8_Activity.jpeg"
contentPage.processPage.imageFiles["_HQzNoXVyEeikbeB96ldyOw,_P-Z28XVyEeikbeB96ldyOw,_BdgxoXV4EeikbeB96ldyOw,_QsUeInV4EeikbeB96ldyOwActivity"]="./../../GamesUp/deliveryprocesses/resources/Game Art Development_DF2D2163_e0394ec4_Activity.jpeg"
contentPage.processPage.elementUrls["_0hXl0XldEeiPve0VZ9wu1A"] = ["Game Publish","GamesUp/deliveryprocesses/Game Publish_BB466C94.html"];
contentPage.processPage.elementUrls["__hq_0HmEEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_C4905F33.html"];
contentPage.processPage.elementUrls["_0g-KkHkYEeiMcpQeZPOdbg"] = ["Integrar Roteiro à Ambientação","GamesUp/deliveryprocesses/Integrar Roteiro à Ambientação_C60EE6B4.html"];
contentPage.processPage.elementUrls["_eGWU0nleEeiPve0VZ9wu1A"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_DBC2497F.html"];
contentPage.processPage.elementUrls["_TDm4YHkXEeiMcpQeZPOdbg"] = ["Feedback Comunidade","GamesUp/deliveryprocesses/Feedback Comunidade_39FD1367.html"];
contentPage.processPage.elementUrls["_hqfKJHmDEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_8856440F.html"];
contentPage.processPage.elementUrls["_3T3GInleEeiPve0VZ9wu1A"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_9993E51B.html"];
contentPage.processPage.elementUrls["_9lCtUHl_EeiCROWijA9fGg"] = ["Publicar Game Para Teste","GamesUp/deliveryprocesses/Publicar Game Para Teste_E6CC9C96.html"];
contentPage.processPage.elementUrls["_54ppMXmBEeiCROWijA9fGg"] = ["Publicar Game Para Teste","GamesUp/deliveryprocesses/Publicar Game Para Teste_25CEC92B.html"];
contentPage.processPage.elementUrls["_AJK6IHmEEeiCROWijA9fGg"] = ["Reunião Com Publisher","GamesUp/deliveryprocesses/Reunião Com Publisher_66E75677.html"];
contentPage.processPage.elementUrls["_ye8JUHmEEeiCROWijA9fGg"] = ["Publisher","GamesUp/deliveryprocesses/Publisher_3F6D6155.html"];
contentPage.processPage.elementUrls["_pHJDsXV3EeikbeB96ldyOw"] = ["Game Art Development","GamesUp/deliveryprocesses/Game Art Development_8C3D48C2.html"];
contentPage.processPage.elementUrls["_3T3GIHleEeiPve0VZ9wu1A"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_A05CF0F5.html"];
contentPage.processPage.elementUrls["_2_2IsnmEEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_6B9AEA03.html"];
contentPage.processPage.elementUrls["_7AJsoXV3EeikbeB96ldyOw"] = ["Script Produce","GamesUp/deliveryprocesses/Script_F0486EC7.html"];
contentPage.processPage.elementUrls["_hmzjcXkUEeiMcpQeZPOdbg"] = ["Publish Demo","GamesUp/deliveryprocesses/Publish Demo_90D5F188.html"];
contentPage.processPage.elementUrls["_XURkEHleEeiPve0VZ9wu1A"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_4910B9A.html"];
contentPage.processPage.elementUrls["_km1jUHl_EeiCROWijA9fGg"] = ["Game Brief","GamesUp/deliveryprocesses/Game Brief_E77B20ED.html"];
contentPage.processPage.elementUrls["_QsUeJHV4EeikbeB96ldyOw"] = ["Game System Project","GamesUp/deliveryprocesses/Game System Project_AA880F5C.html"];
contentPage.processPage.elementUrls["_lkgN8HV4EeikbeB96ldyOw"] = ["Game Publish","GamesUp/deliveryprocesses/Game Publish_72AB7642.html"];
contentPage.processPage.elementUrls["_54qQQHmBEeiCROWijA9fGg"] = ["Game Brief","GamesUp/deliveryprocesses/Game Brief_2D787197.html"];
contentPage.processPage.elementUrls["_mHZH0XkWEeiMcpQeZPOdbg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_A5221BD1.html"];
contentPage.processPage.elementUrls["_f8k5cHkYEeiMcpQeZPOdbg"] = ["Criar Missões Principais","GamesUp/deliveryprocesses/Criar Missões Principais_1E2DA503.html"];
contentPage.processPage.elementUrls["_1W2xoHmEEeiCROWijA9fGg"] = ["Publisher","GamesUp/deliveryprocesses/Publisher_3716F929.html"];
contentPage.processPage.elementUrls["_BdgxoXV4EeikbeB96ldyOw"] = ["Iteration Dev 2","GamesUp/deliveryprocesses/Iteration_C75A008.html"];
contentPage.processPage.elementUrls["_ifAEUXVyEeikbeB96ldyOw"] = ["Game Concept Art","GamesUp/deliveryprocesses/Game Concept Art_8A625A15.html"];
contentPage.processPage.elementUrls["_3DmcMXkUEeiMcpQeZPOdbg"] = ["Game Test","GamesUp/deliveryprocesses/Ga_6B3CFF30.html"];
contentPage.processPage.elementUrls["_6q5LoHkXEeiMcpQeZPOdbg"] = ["Teste de Software","GamesUp/deliveryprocesses/Teste de Software_2E50106C.html"];
contentPage.processPage.elementUrls["_S2ysUHmDEeiCROWijA9fGg"] = ["Definir Atividades de Mudança","GamesUp/deliveryprocesses/Definir Atividades de Mudança_2BA070CF.html"];
contentPage.processPage.elementUrls["_elZgkHkXEeiMcpQeZPOdbg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_BAF54AB2.html"];
contentPage.processPage.elementUrls["_UNUfsXV4EeikbeB96ldyOw"] = ["Community Meeting","GamesUp/deliveryprocesses/Community Meeting_4628F6FB.html"];
contentPage.processPage.elementUrls["_F0EAYHmEEeiCROWijA9fGg"] = ["Analisar Feedback da Comunidade","GamesUp/deliveryprocesses/Pu_71A05B79.html"];
contentPage.processPage.elementUrls["_qFRlIHmDEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_CB188F51.html"];
contentPage.processPage.elementUrls["_XURkE3leEeiPve0VZ9wu1A"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_66A1D585.html"];
contentPage.processPage.elementUrls["_kVCE0HmDEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_53D5FEA8.html"];
contentPage.processPage.elementUrls["_o2FOIHmDEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_9A36CCAE.html"];
contentPage.processPage.elementUrls["_gKKe8XkXEeiMcpQeZPOdbg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_DC069B1F.html"];
contentPage.processPage.elementUrls["_-y6R0HmDEeiCROWijA9fGg"] = ["Pesquisa de Publishers","GamesUp/deliveryprocesses/Pesquisa de Publishers_26CB70C3.html"];
contentPage.processPage.elementUrls["_3T3GI3leEeiPve0VZ9wu1A"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_26DBAE0.html"];
contentPage.processPage.elementUrls["_mHZH0nkWEeiMcpQeZPOdbg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_93BB2FE7.html"];
contentPage.processPage.elementUrls["_gSCJcHmDEeiCROWijA9fGg"] = ["Community","GamesUp/deliveryprocesses/Community_4158289B.html"];
contentPage.processPage.elementUrls["_nadnUHkYEeiMcpQeZPOdbg"] = ["Arquiteturar Personagens","GamesUp/deliveryprocesses/Arquiteturar Personagens_C635552.html"];
contentPage.processPage.elementUrls["_Divd0nlfEeiPve0VZ9wu1A"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_A445F033.html"];
contentPage.processPage.elementUrls["_eGWU0HleEeiPve0VZ9wu1A"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_E28B5559.html"];
contentPage.processPage.elementUrls["_mcjyAHmDEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_2299732F.html"];
contentPage.processPage.elementUrls["_-OgkEXleEeiPve0VZ9wu1A"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_2B6967BA.html"];
contentPage.processPage.elementUrls["_kPtasHV3EeikbeB96ldyOw"] = ["Iteration Dev","GamesUp/deliveryprocesses/Iteration Dev_92A4AE12.html"];
contentPage.processPage.elementUrls["_hqfKIHmDEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_C3C461F0.html"];
contentPage.processPage.elementUrls["_gdbg8XleEeiPve0VZ9wu1A"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_F606A0E3.html"];
contentPage.processPage.elementUrls["_kC3ZYHkYEeiMcpQeZPOdbg"] = ["Desenvolver Ambiente Para Teste","GamesUp/deliveryprocesses/Desenvolver Ambiente Para Teste_A9E33D90.html"];
contentPage.processPage.elementUrls["_vc-fEHmCEeiCROWijA9fGg"] = ["Incrementar Funcionalidades do Jogo","GamesUp/deliveryprocesses/Incrementar Funcionalidades do Jogo_2083CB0B.html"];
contentPage.processPage.elementUrls["_Ts5NUXkUEeiMcpQeZPOdbg"] = ["Publishers Meet","GamesUp/deliveryprocesses/Publishers Meet_ACBD47B9.html"];
contentPage.processPage.elementUrls["_jttwsHmEEeiCROWijA9fGg"] = ["Publicar Game na Publisher","GamesUp/deliveryprocesses/Publicar Game na Publisher_9487C166.html"];
contentPage.processPage.elementUrls["_fUcfoXleEeiPve0VZ9wu1A"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_7D98CFC.html"];
contentPage.processPage.elementUrls["_mHYgwHkWEeiMcpQeZPOdbg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_1EF9F25A.html"];
contentPage.processPage.elementUrls["_49PCcHmEEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_AA95ACA1.html"];
contentPage.processPage.elementUrls["_z6vyQHl_EeiCROWijA9fGg"] = ["Compilar Demo do Jogo","GamesUp/deliveryprocesses/Compilar Demo do Jogo_7DC74AF5.html"];
contentPage.processPage.elementUrls["_DcdaYHmFEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_2CE66D0.html"];
contentPage.processPage.elementUrls["_3T3GJHleEeiPve0VZ9wu1A"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_64EED314.html"];
contentPage.processPage.elementUrls["_PzM3kHkXEeiMcpQeZPOdbg"] = ["Publicação das Artes para Feedback","GamesUp/deliveryprocesses/Publicação das Artes para Feedback_D886AAAE.html"];
contentPage.processPage.elementUrls["_oQpd4HkXEeiMcpQeZPOdbg"] = ["Analise de Feedback","GamesUp/deliveryprocesses/Analise de Feedback_EB9E628B.html"];
contentPage.processPage.elementUrls["_7qxwQXVyEeikbeB96ldyOw"] = ["Community Meeting","GamesUp/deliveryprocesses/Community Meeting_AB9B1131.html"];
contentPage.processPage.elementUrls["_LoergHmDEeiCROWijA9fGg"] = ["Publicar Game Brief","GamesUp/deliveryprocesses/Publicar Game Brief_6A5D9B34.html"];
contentPage.processPage.elementUrls["_-0o6sHmEEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_6F9D1163.html"];
contentPage.processPage.elementUrls["_wMZMcHkXEeiMcpQeZPOdbg"] = ["Alterações na Art","GamesUp/deliveryprocesses/Alterações na Art_A1F9B0AF.html"];
contentPage.processPage.elementUrls["_zT36wHkXEeiMcpQeZPOdbg"] = ["Detalhamento Sobre Historia","GamesUp/deliveryprocesses/Detalhamento Sobre Historia_2528D0AF.html"];
contentPage.processPage.elementUrls["_s-CPgHkWEeiMcpQeZPOdbg"] = ["Realizar Breve Historia","GamesUp/deliveryprocesses/Breve Historia_46A51708.html"];
contentPage.processPage.elementUrls["_wESj4HkYEeiMcpQeZPOdbg"] = ["Arquiteturar Ações do Personagem","GamesUp/deliveryprocesses/Arquiteturar Ações do Personagem_7725217B.html"];
contentPage.processPage.elementUrls["_aFJBcHkXEeiMcpQeZPOdbg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_69DD5743.html"];
contentPage.processPage.elementUrls["_Ll-eIXVyEeikbeB96ldyOw"] = ["Game Design","GamesUp/deliveryprocesses/Game Design_FEA2D658.html"];
contentPage.processPage.elementUrls["_aP8YMXVyEeikbeB96ldyOw"] = ["Brain Storm","GamesUp/deliveryprocesses/Brain Storm_91F74CC.html"];
contentPage.processPage.elementUrls["_CT8AoHkYEeiMcpQeZPOdbg"] = ["Reunião Escolha de Software","GamesUp/deliveryprocesses/Reunião Escolha de Software_D03574F5.html"];
contentPage.processPage.elementUrls["_1CATMXV3EeikbeB96ldyOw"] = ["Game System Project","GamesUp/deliveryprocesses/Game System Project_BAA5923B.html"];
contentPage.processPage.elementUrls["_hqfKInmDEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_BCFB5616.html"];
contentPage.processPage.elementUrls["_kVBdwHmDEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_D84BB541.html"];
contentPage.processPage.elementUrls["_2p7tEHkWEeiMcpQeZPOdbg"] = ["Desenvolver Historia","GamesUp/deliveryprocesses/Desenvolver Historia_5FB89FFE.html"];
contentPage.processPage.elementUrls["_8ADvgnleEeiPve0VZ9wu1A"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_77F60003.html"];
contentPage.processPage.elementUrls["_XtaKgHkWEeiMcpQeZPOdbg"] = ["Definir Estilo de Gameplay","GamesUp/deliveryprocesses/New Task Descriptor_3_B599B567.html"];
contentPage.processPage.elementUrls["_1gT6gHmCEeiCROWijA9fGg"] = ["Incremento do Ambiente de Jogo","GamesUp/deliveryprocesses/Incremento do Ambiente de Jogo_E5F1B09B.html"];
contentPage.processPage.elementUrls["_1W08cHmEEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_C66442B7.html"];
contentPage.processPage.elementUrls["_hiDpgHkYEeiMcpQeZPOdbg"] = ["Criar Missões Secundarias","GamesUp/deliveryprocesses/Criar Missões Secundarias_C3647F70.html"];
contentPage.processPage.elementUrls["_e7szMHmEEeiCROWijA9fGg"] = ["Analisar Possiveis Melhorias","GamesUp/deliveryprocesses/Analisar Possiveis Melhorias_472E5AD8.html"];
contentPage.processPage.elementUrls["_2Iu6gHmEEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_821E1CDD.html"];
contentPage.processPage.elementUrls["_l5mZcHmEEeiCROWijA9fGg"] = ["Realizar Possiveis Updates","GamesUp/deliveryprocesses/Verificar Possiveis Updates_9D16BA7F.html"];
contentPage.processPage.elementUrls["_mHZH0HkWEeiMcpQeZPOdbg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_9A843BC1.html"];
contentPage.processPage.elementUrls["_4l8OsHmCEeiCROWijA9fGg"] = ["Incremento Modelo dos Personagens","GamesUp/deliveryprocesses/Incremento Modelo dos Personagens_AF465EE6.html"];
contentPage.processPage.elementUrls["_-E9TsnVyEeikbeB96ldyOw"] = ["Refine Concept","GamesUp/deliveryprocesses/Refine Concept_2AF1923F.html"];
contentPage.processPage.elementUrls["_du_nkHkYEeiMcpQeZPOdbg"] = ["Desenvolver Roteiro","GamesUp/deliveryprocesses/Desenvolver Roteiro_257D77FF.html"];
contentPage.processPage.elementUrls["_9VtMEHkXEeiMcpQeZPOdbg"] = ["Minigame Para Analise","GamesUp/deliveryprocesses/Minigame Para Analise_FC4E65BA.html"];
contentPage.processPage.elementUrls["_fgJZgHmDEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_F9201D35.html"];
contentPage.processPage.elementUrls["_hqfKI3mDEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_25D52BDB.html"];
contentPage.processPage.elementUrls["_Y0C4cHmEEeiCROWijA9fGg"] = ["Verificar Funcionamento Game","GamesUp/deliveryprocesses/Analis_DA5566F1.html"];
contentPage.processPage.elementUrls["_elZgknkXEeiMcpQeZPOdbg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_B42C3ED8.html"];
contentPage.processPage.elementUrls["__OqGsnVyEeikbeB96ldyOw"] = ["Engine Choose","GamesUp/deliveryprocesses/Engine Choose_28C98A52.html"];
contentPage.processPage.elementUrls["_cYaroHkXEeiMcpQeZPOdbg"] = ["Community","GamesUp/deliveryprocesses/Community_FC963541.html"];
contentPage.processPage.elementUrls["_4MLY8HmEEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_B024EC9A.html"];
contentPage.processPage.elementUrls["_-FFtEHmEEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_E8E3E06E.html"];
contentPage.processPage.elementUrls["_5d-YAHmEEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_34F0B366.html"];
contentPage.processPage.elementUrls["_bLQc4nmDEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_EB788279.html"];
contentPage.processPage.elementUrls["_RbGKYHmDEeiCROWijA9fGg"] = ["Analise de Feedback","GamesUp/deliveryprocesses/Analise de Feedback_B3D52226.html"];
contentPage.processPage.elementUrls["_-FFtEnmEEeiCROWijA9fGg"] = ["Publisher","GamesUp/deliveryprocesses/Publisher_E21AD494.html"];
contentPage.processPage.elementUrls["_Divd0HlfEeiPve0VZ9wu1A"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_AB0EFC0D.html"];
contentPage.processPage.elementUrls["_XURkEnleEeiPve0VZ9wu1A"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_FDC7FFC0.html"];
contentPage.processPage.elementUrls["_HQzNoXVyEeikbeB96ldyOw"] = ["LifeCycleGameUP","GamesUp/deliveryprocesses/LifeCycleGameUP_EF704A17.html"];
contentPage.processPage.elementUrls["_J15oIHkWEeiMcpQeZPOdbg"] = ["Definir Escopo do Jogo","GamesUp/deliveryprocesses/New Task Descriptor_2_214DA720.html"];
contentPage.processPage.elementUrls["_9hFyIHkWEeiMcpQeZPOdbg"] = ["Descrever Ambientação","GamesUp/deliveryprocesses/Ambientação_51B00F21.html"];
contentPage.processPage.elementUrls["_54qQQXmBEeiCROWijA9fGg"] = ["Compilar Demo do Jogo","GamesUp/deliveryprocesses/Compilar Demo do Jogo_381651A7.html"];
contentPage.processPage.elementUrls["_2_2IsXmEEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_7D01D5ED.html"];
contentPage.processPage.elementUrls["_QsUeInV4EeikbeB96ldyOw"] = ["Game Art Development","GamesUp/deliveryprocesses/Game Art Development_DF2D2163.html"];
contentPage.processPage.elementUrls["_OQnycHmDEeiCROWijA9fGg"] = ["Feedback da Comunidade","GamesUp/deliveryprocesses/Feedback da Comunidade_3613B315.html"];
contentPage.processPage.elementUrls["_W37KAXmEEeiCROWijA9fGg"] = ["Game Update","GamesUp/deliveryprocesses/Game Update_810B660B.html"];
contentPage.processPage.elementUrls["_tbIQoHkVEeiMcpQeZPOdbg"] = ["Reunião Com Equipe Para Criação Jogo","GamesUp/deliveryprocesses/New Task Descriptor_6EFEB40E.html"];
contentPage.processPage.elementUrls["_tVXfgHkYEeiMcpQeZPOdbg"] = ["Desenvolver Funcionalidades do Jogo","GamesUp/deliveryprocesses/Desenvolver Movimentação_324BF433.html"];
contentPage.processPage.elementUrls["_n3mMoXmDEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_6E25D31.html"];
contentPage.processPage.elementUrls["_Cnb24HmFEeiCROWijA9fGg"] = ["Game Artist","GamesUp/deliveryprocesses/Game_Artist_C39EB14.html"];
contentPage.processPage.elementUrls["_Cli18HmEEeiCROWijA9fGg"] = ["Publicar Game Demo na Publisher","GamesUp/deliveryprocesses/Publicar Game Test na Publisher_33369925.html"];
contentPage.processPage.elementUrls["_q_mp8HmEEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_F6EF1225.html"];
contentPage.processPage.elementUrls["_hnnhoXV4EeikbeB96ldyOw"] = ["Refine Concept","GamesUp/deliveryprocesses/Refine Concept_FD0FAB35.html"];
contentPage.processPage.elementUrls["_hXgb0XkXEeiMcpQeZPOdbg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_CE760974.html"];
contentPage.processPage.elementUrls["_bLQc4HmDEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_F2418E53.html"];
contentPage.processPage.elementUrls["_P-Z28XVyEeikbeB96ldyOw"] = ["Game Development","GamesUp/deliveryprocesses/Game Development_AFE68746.html"];
contentPage.processPage.elementUrls["_m0qIYXkUEeiMcpQeZPOdbg"] = ["Community Meeting","GamesUp/deliveryprocesses/Community Meeting_DBA61E78.html"];
contentPage.processPage.elementUrls["_z6OtgHmCEeiCROWijA9fGg"] = ["Desenvolvimento Roteiro","GamesUp/deliveryprocesses/Desenvolvimento Roteiro_21E76724.html"];
contentPage.processPage.elementUrls["_2_2IsHmEEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_7263F5DD.html"];
contentPage.processPage.elementUrls["_j-bA8HV4EeikbeB96ldyOw"] = ["Game Demo","GamesUp/deliveryprocesses/Game Demo_60C4651E.html"];
contentPage.processPage.elementUrls["_EgW8oXlfEeiPve0VZ9wu1A"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_1D058EAE.html"];
contentPage.processPage.elementUrls["_mckZEHmDEeiCROWijA9fGg"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_34E0FBAB.html"];
contentPage.processPage.elementUrls["_ye7iQHmEEeiCROWijA9fGg"] = ["Project Manager","GamesUp/deliveryprocesses/Project_Manager_2D25D8D9.html"];
contentPage.processPage.elementUrls["_6FZkYHmEEeiCROWijA9fGg"] = ["Story Teller","GamesUp/deliveryprocesses/Story_Teller_DCA46A14.html"];
contentPage.processPage.elementUrls["_F-9WUHkXEeiMcpQeZPOdbg"] = ["Desenvolver Personagens","GamesUp/deliveryprocesses/Desenvolvimento Personagens_BC1319B9.html"];
contentPage.processPage.elementUrls["_8ADvgHleEeiPve0VZ9wu1A"] = ["Game Programmer","GamesUp/deliveryprocesses/Game_Programmer_7EBF0BDD.html"];
